### ISSUE TITLE
Feature extraction code of the Slow-Fast Model

### ISSUE THREAD

**Issue by StevenLauHKHK** [epic-kitchens/C10-epic-sounds-detection#3]
Hi,

Could you provide the feature extraction code for the Slow-Fast model?
In the current version, we can only download the features, but we don't know how the features from the slow-fast model are extracted. In particular, what was the resolution of the spectrogram used to extract the features?

In the code, I also see C x T (line 79, in the dataset folder, epic_kitchen.py). What does C and T represent? 

Thanks in advance for your anticipation.

**Comment by JacobChalk** [comment]
Hi,

We provide only the features necessary to replicate our results. You may refer to the [Auditory SlowFast GitHub Page](https://github.com/ekazakos/auditory-slow-fast) if you wish to modify the features that you use. 

In our case, we used the [SlowFast_R50 config](https://github.com/ekazakos/auditory-slow-fast/blob/main/configs/EPIC-KITCHENS/SLOWFAST_R50.yaml), and modified the `CLIP_SECS 0.999` and `NUM_FRAMES 200`. This resulted in spectrograms of size 200x128. The 128 comes from the number of Mel bands as seen in the code [here](https://github.com/ekazakos/auditory-slow-fast/blob/6af3fd7277e278315ebbed1430d682dd64a3a80d/slowfast/datasets/audio_loader_epic.py#L62).

The C x T you are referring to is ActionFormer specific. Namely, the C relates to the channel dimension of the input features (2304 for Auditory SlowFast features) and the T refers to the number of time steps (features) for the current video. T will vary per video, but will be restricted to the `max_seq_len` which we set as [9216](https://github.com/epic-kitchens/C10-epic-sounds-detection/blob/fc430786fd956ecd6c96ce622da454c47f568ade/baseline/configs/epic_sounds_auditory_slowfast.yaml#L16).

**Comment by StevenLauHKHK** [comment]
Hi Jacob! 

Thank you for the prompt response. One last question: Did you use overlapping window when extracting the features from the slow-fast model? If yes, what was the stride of the window that you used?

Thank you

**Comment by JacobChalk** [comment]
Hi Steven,

Yes, we used an overlapping window for our feature extraction, we densely extracted 1 second features with a stride of 0.2 seconds i.e. [0-1, 0.2-1.2, 0.4-1.4, ...] and so on. Hope this helps!
